### ISSUE TITLE
Wifi does not work after installing the kernel, which (the kernel) is made from your sources

### ISSUE THREAD

**Issue by pasha6789** [SunnyRaj84348/android_kernel_xiaomi_msm8917#5]
Wifi does not work after building the kernel from cm-14.1 source and its firmware on Redmi 5a on android cm -14.1 (downloaded from here https://forum.xda-developers.com/xiaomi-redmi-5a/development/unofficial-lineage- os-14-1-redmi-5a-t3773985).
Why did wifi stop working? How to fix it?

**Comment by SunnyRaj84348** [comment]
We are not using prebuilt wlan module instead we are compiling and using from kernel source itself
